"""Backend for the /forecast what-if tool: a production port of ``working/forecasts.ipynb``.

The notebook is the design surface and remains the source of truth for the model; this module is a
faithful port of its computation so the website can answer "what if?" questions interactively. It has
two halves:

* **A context built once** (``get_context``) from the read-only attendance database — the behavioural
  models that don't depend on the committee's choices: Level 1 sign-ups (OLS), the Level 1 weekly
  attendance curve, Level 2 / social / weekender turnout, the discounted-ticket fractions, and the
  Level 2 loyalty survival curve. Only SELECTs run, and only counts and dates are read — never PII.
* **A per-request forecast** (``predict``) that takes the committee's parameter overrides, rebuilds
  the calendar and the money ledger, and propagates the attendance uncertainty through it with the
  **unscented transform** (the sigma-point method — cheap enough for live use, unlike Monte Carlo).

The sensitive financial defaults (prices, pay rates, the opening bank balance, the fitted band fee and
membership figures) are **not** committed: they load from a key,value CSV under ``working/`` — see
``config.FORECAST_DEFAULTS_PATH``, regenerated by ``working/gen_defaults.py`` — mirroring how
``attendance/early_term_stats.csv`` supplies data the schema can't. Everything a viewer can change has a
provenance note in the UI (see the frontend's control metadata). The scenario *download* is still xlsx.
"""

import csv
import datetime
import io
import sqlite3
import threading
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import openpyxl
from dateutil.easter import easter
from scipy import stats
from scipy.optimize import curve_fit

from esds_apps import config

MON, THU, FRI, SUN = 0, 3, 4, 6
TERM_MIN_WEEKS, TERM_MAX_WEEKS = 5, 7
_DECEMBER = 12
_SEPTEMBER = 9
_ACADEMIC_YEAR_START_MONTH = 8
_SNAP_HALF_WEEK = 3  # a social lands on the nearest matching weekday within +/- this many days
# Data-filter thresholds for the behavioural fits (mirroring the notebook).
_FIRST_FULL_YEAR = 2022  # the L1 sign-ups regression uses the full six-term years from here
_MIN_WEEKS_FOR_CURVE = 4  # a term needs this many weekly points to shape the attendance curve
_MIN_WK1_HEADCOUNT = 10  # ... and a week-1 headcount of at least this to be trusted
_FIRST_COMPLETE_L2_YEAR = 2023  # earlier Level 2 terms logged mostly enrolment, so are excluded
_MIN_L2_NIGHT = 15  # ... as are terms whose mean per-night reads implausibly low
_MIN_SOCIAL_TOTAL = 10  # socials below this headcount are booking exports, not real turnout
_SURVIVAL_EPS = 1e-4  # stop summing the loyalty survival tail once it falls below this
_MAX_SURVIVAL_NIGHTS = 1000  # ... or this many nights, whichever comes first

# The uncertain inputs propagated through the ledger, in vector order. The first six are the Level 1
# term sign-ups (correlated, carrying the regression covariance); the rest are independent.
INPUT_NAMES = [f'L1 term {p}' for p in range(1, 7)] + [
    'Level 2 / night',
    'social attendance',
    'Christmas party',
    'social-only / night',
    'weekender audience',
    'members',
    'L1 discounted share',
    'L2 discounted share',
    'social discounted share',
    'weekender discounted share',
    'loyalty refunds',
    'band fee',
]

# The overhead lines the committee can edit (final annual £; Google Workspace is derived separately).
OVERHEAD_KEYS = [
    'website',
    'email_marketing',
    'insurance',
    'storage_container',
    'spotify',
    'survey_monkey',
    'pat_testing',
    'equipment_recap',
    'society_phone',
    'posters',
    'stationery',
    'canva',
]


# --------------------------------------------------------------------------------------------------
# Calendar (deterministic given the forecast year and the two social-count knobs)
# --------------------------------------------------------------------------------------------------
def _nth_weekday(year: int, month: int, weekday: int, n: int) -> date:
    d = date(year, month, 1)
    return d + timedelta(days=(weekday - d.weekday()) % 7 + 7 * (n - 1))


def _last_weekday(year: int, month: int, weekday: int) -> date:
    nxt = date(year + 1, 1, 1) if month == _DECEMBER else date(year, month + 1, 1)
    d = nxt - timedelta(days=1)
    return d - timedelta(days=(d.weekday() - weekday) % 7)


def _week_monday(d: date) -> date:
    return d - timedelta(days=d.weekday())


def _thursdays_between(first: date, last: date) -> list[date]:
    out, d = [], first
    while d <= last:
        out.append(d)
        d += timedelta(days=7)
    return out


def _snap_to_weekday(d: date, weekday: int) -> date:
    diff = weekday - d.weekday()
    if diff > _SNAP_HALF_WEEK:
        diff -= 7
    if diff < -_SNAP_HALF_WEEK:
        diff += 7
    return d + timedelta(days=diff)


def _best_split(n_weeks: int) -> list[int]:
    """Most-even way to cut n consecutive weeks into 5-7 week terms; longer term first on ties."""
    opts: list[list[int]] = []

    def rec(rem, acc):
        if rem == 0:
            opts.append(list(acc))
            return
        for w in range(TERM_MIN_WEEKS, TERM_MAX_WEEKS + 1):
            if w <= rem:
                acc.append(w)
                rec(rem - w, acc)
                acc.pop()

    rec(n_weeks, [])
    if not opts:
        raise ValueError(f'no 5-7 week split covers {n_weeks} weeks')
    opts.sort(key=lambda s: (max(s) - min(s), [-x for x in s]))
    return opts[0]


def build_calendar(ay: int) -> dict:
    """Derive the six-term teaching calendar and the fixed party dates for academic year ``ay``."""
    term1_first = _nth_weekday(ay, 9, THU, 2)
    xmas = date(ay, 12, 25)
    xmas_party = _week_monday(xmas) - timedelta(days=7) + timedelta(days=THU)
    term2_last = xmas_party - timedelta(days=7)
    term3_first = _nth_weekday(ay + 1, 1, THU, 2)
    eoy_party = _last_weekday(ay + 1, 6, THU)
    final_term_last = eoy_party - timedelta(days=7)
    easter_thu = _week_monday(easter(ay + 1)) + timedelta(days=THU)

    pre_xmas = _thursdays_between(term1_first, term2_last)
    post_all = _thursdays_between(term3_first, final_term_last)
    post_xmas = [d for d in post_all if d != easter_thu]
    pre_easter = [d for d in post_xmas if d < easter_thu]
    post_easter = [d for d in post_xmas if d > easter_thu]

    terms, num = [], 1
    for region in (pre_xmas, pre_easter, post_easter):
        i = 0
        for weeks in _best_split(len(region)):
            chunk = region[i : i + weeks]
            i += weeks
            terms.append({'term': num, 'start': chunk[0], 'end': chunk[-1], 'weeks': weeks, 'thursdays': chunk})
            num += 1

    return {'ay': ay, 'terms': terms, 'xmas_party': xmas_party, 'eoy_party': eoy_party, 'first_class': term1_first}


def place_socials(cal: dict, n_tea: int, have_weekender: bool) -> list[tuple[str, date]]:
    """Evenly space the tea dances (+ optional weekender) around the two fixed parties."""
    start, xmas, eoy = cal['first_class'], cal['xmas_party'], cal['eoy_party']
    n_slots = n_tea + (1 if have_weekender else 0) + 2
    grid = [start + (eoy - start) * (i + 1) / n_slots for i in range(n_slots)]
    labels: list = [None] * n_slots
    labels[-1] = ('End-of-year party', eoy)
    xi = min(range(n_slots - 1), key=lambda i: abs((grid[i] - xmas).days))
    labels[xi] = ('Christmas party', xmas)
    free = [i for i in range(n_slots) if labels[i] is None]
    if have_weekender:
        wi = free.pop()  # latest free slot -> weekender (spring)
        labels[wi] = ('Weekender', _snap_to_weekday(grid[wi], FRI))
    for j, i in enumerate(free, 1):
        labels[i] = (f'Tea dance {j}', _snap_to_weekday(grid[i], SUN))
    return labels


def _ay_of(d) -> int:
    dt = date.fromisoformat(d) if isinstance(d, str) else d
    return dt.year if dt.month >= _ACADEMIC_YEAR_START_MONTH else dt.year - 1


def _z(confidence: float) -> float:
    """Two-sided normal critical value for a confidence level (e.g. 0.95 -> 1.96)."""
    return float(stats.norm.ppf(0.5 + confidence / 2))


# --------------------------------------------------------------------------------------------------
# Level 2 loyalty: survival families
# --------------------------------------------------------------------------------------------------
_FAMILIES = {
    'geometric': (lambda k, r: r ** (k - 1), [0.7], (1e-3, 1 - 1e-3)),
    'power': (lambda k, a: k ** (-a), [1.0], (1e-3, 10.0)),
    'weibull': (lambda k, b, c: np.exp(-(((k - 1) / b) ** c)), [3.0, 1.0], ([0.1, 0.1], [50.0, 5.0])),
}


def _survival(counts):
    ks = np.arange(1, max(counts) + 1)
    return ks, np.array([np.mean([c >= k for c in counts]) for k in ks])


def _fit_family(name, ks, s):
    f, p0, bnds = _FAMILIES[name]
    popt, _ = curve_fit(f, ks, s, p0=p0, bounds=bnds, maxfev=10000)
    r2 = 1 - np.sum((s - f(ks, *popt)) ** 2) / np.sum((s - s.mean()) ** 2)
    return popt, float(r2)


# --------------------------------------------------------------------------------------------------
# The context: everything derived from the read-only attendance DB (built once, cached)
# --------------------------------------------------------------------------------------------------
@dataclass
class ForecastContext:
    """Behavioural models fitted from the attendance DB, plus the financial defaults spreadsheet."""

    # Level 1 sign-ups regression (predict per-term interest at a given forecast year)
    beta: np.ndarray
    s2: float
    xtxi: np.ndarray
    dof: int
    l1_attend_curve: list[float]  # fraction of a term's sign-ups attending each week
    l1_history: list[dict]  # per-term interest, for the detailed chart
    # turnout series (values kept so predictive variance can be recomputed)
    l2_vals: list[float]
    soc_vals: list[float]
    xmas_vals: list[float]
    social_only_vals: list[float]
    # weekender recurring-audience model
    wk_mix: dict
    # discounted-ticket shares and their binomial sample sizes
    fractions: dict  # {'l1':.., 'l2':.., 'soc':.., 'wk':..}
    frac_n: dict  # {'l1':N, ...}
    # Level 2 loyalty survival
    loyalty_family: str
    loyalty_popt: list[float]
    loyalty_n_dancers: int
    loyalty_obs_thu: int
    survival_l2: dict  # empirical + fitted curve, for the detailed chart
    # sensitive financial defaults (from the spreadsheet)
    defaults: dict = field(default_factory=dict)


_CONTEXT: ForecastContext | None = None
_LOCK = threading.Lock()


def _coerce(s: str):
    """Coerce a CSV cell to None / bool / int / float / str (values are typed by their spelling)."""
    s = s.strip()
    if s == '':
        return None
    if s in ('True', 'False'):
        return s == 'True'
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        return s


def _load_defaults() -> dict:
    """Read the financial defaults from the (gitignored) key,value CSV under working/.

    Kept off GitHub because these are the society's real prices, pay rates and bank balance. Types are
    inferred from how each value is written (blank -> None, True/False -> bool, else int/float/str).
    Regenerate the file with working/gen_defaults.py.
    """
    path = Path(config.FORECAST_DEFAULTS_PATH)
    if not path.exists():
        raise FileNotFoundError(path)
    scalars = {}
    with open(path, newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader, None)  # skip the 'key,value' header
        for row in reader:
            if not row or not row[0].strip():
                continue
            scalars[row[0].strip()] = _coerce(row[1] if len(row) > 1 else '')
    return scalars


def _build_context() -> ForecastContext:  # noqa: PLR0915  (a single sweep of the read-only DB)
    db = Path(config.ATTENDANCE_DB_PATH)
    if not db.exists():
        raise FileNotFoundError(db)

    with sqlite3.connect(f'file:{db}?mode=ro', uri=True) as conn:
        # ---- Level 1 terms: interest (= reg + waitlist) and the weekly attendance series ----
        l1_rows = []
        for eid, start, weeks in conn.execute(
            'SELECT e.event_id, MIN(a.date), COUNT(DISTINCT a.date) FROM event e JOIN activity a USING(event_id) '
            "WHERE e.event_type='course' AND a.difficulty='Level 1' GROUP BY e.event_id "
            'HAVING COUNT(DISTINCT a.date) >= 3 ORDER BY MIN(a.date)'
        ):
            reg = conn.execute(
                'SELECT COUNT(DISTINCT at.dancer_id) FROM attendance at JOIN activity a USING(activity_id) '
                'WHERE a.event_id = ?',
                (eid,),
            ).fetchone()[0]
            wl = conn.execute(
                'SELECT COALESCE(SUM(head_count), 0) FROM waitlist WHERE event_id = ?', (eid,)
            ).fetchone()[0]
            weekly = [
                t
                for (t,) in conn.execute(
                    'SELECT aa.total FROM activity a JOIN activity_attendance aa USING(activity_id) '
                    "WHERE a.event_id = ? AND a.difficulty='Level 1' ORDER BY a.date",
                    (eid,),
                )
            ]
            l1_rows.append({'ay': _ay_of(start), 'weeks': weeks, 'interest': reg + wl, 'weekly': weekly})
        # position of each term within its academic year
        seen: dict[int, int] = {}
        for r in l1_rows:
            seen[r['ay']] = seen.get(r['ay'], 0) + 1
            r['pos'] = seen[r['ay']]

        # ---- Level 1 sign-ups OLS: interest ~ year + C(term position) over the full six-term years ----
        d = [r for r in l1_rows if r['ay'] >= _FIRST_FULL_YEAR]
        x = np.column_stack(
            [
                np.ones(len(d)),
                np.array([r['ay'] for r in d]) - 2024,
                *[np.array([1.0 if r['pos'] == p else 0.0 for r in d]) for p in range(2, 7)],
            ]
        )
        y = np.array([r['interest'] for r in d], float)
        beta, *_ = np.linalg.lstsq(x, y, rcond=None)
        resid = y - x @ beta
        dof = len(y) - x.shape[1]
        s2 = float(resid @ resid / dof)
        xtxi = np.linalg.inv(x.T @ x)

        # ---- Level 1 weekly attendance as a fraction of sign-ups (curve for the per-night what-if) ----
        fracs = [
            [h / r['interest'] for h in r['weekly']]
            for r in l1_rows
            if len(r['weekly']) >= _MIN_WEEKS_FOR_CURVE
            and r['weekly']
            and r['weekly'][0] >= _MIN_WK1_HEADCOUNT
            and r['interest']
        ]
        max_wk = max(len(a) for a in fracs)
        l1_attend_curve = [float(np.mean([a[w] for a in fracs if len(a) > w])) for w in range(max_wk)]

        # ---- Level 2 per-night turnout (complete recent terms only) ----
        l2_vals = [
            mt
            for (start, nights, mt) in conn.execute(
                'SELECT MIN(a.date), COUNT(DISTINCT a.date), AVG(aa.total) FROM event e '
                'JOIN activity a USING(event_id) JOIN activity_attendance aa USING(activity_id) '
                "WHERE e.event_type='course' AND a.difficulty='Level 2' GROUP BY e.event_id"
            )
            if _ay_of(start) >= _FIRST_COMPLETE_L2_YEAR and mt and mt > _MIN_L2_NIGHT
        ]

        # ---- Standalone socials: regular vs Christmas, workshop-paired dropped; the 30th never enters ----
        workshop_dates = {
            dd
            for (dd,) in conn.execute(
                "SELECT DISTINCT a.date FROM event e JOIN activity a USING(event_id) WHERE e.event_type='workshop'"
            )
        }
        soc_vals, xmas_vals = [], []
        for name, dd, tot in conn.execute(
            'SELECT e.name, MIN(a.date), SUM(aa.total) FROM event e JOIN activity a USING(event_id) '
            "JOIN activity_attendance aa USING(activity_id) WHERE e.event_type='social' "
            "AND e.name NOT LIKE '%30 Years%' GROUP BY e.event_id"
        ):
            if tot is None or tot <= _MIN_SOCIAL_TOTAL:
                continue
            if 'Christmas' in name or 'Xmas' in name:
                xmas_vals.append(tot)
            elif dd not in workshop_dates:
                soc_vals.append(tot)
        social_only_vals = [
            n / k
            for n, k in conn.execute(
                'SELECT SUM(aa.total), COUNT(DISTINCT a.date) FROM event e JOIN activity a USING(event_id) '
                "JOIN activity_attendance aa USING(activity_id) WHERE e.event_type='course' "
                "AND a.activity_type='social' AND a.date >= '2026-01-01' GROUP BY e.event_id"
            )
        ]

        def disc_named(where):
            r = dict(
                conn.execute(
                    "SELECT CASE WHEN at.ticket_type='ordinary' THEN 'ord' ELSE 'disc' END, COUNT(*) "
                    'FROM attendance at JOIN activity a USING(activity_id) JOIN event e USING(event_id) '
                    f"WHERE {where} AND at.ticket_type IN ('ordinary','member','concession','member_or_concession') "
                    'GROUP BY 1'
                ).fetchall()
            )
            n = r.get('disc', 0) + r.get('ord', 0)
            return r.get('disc', 0) / n, n

        def disc_agg(where):
            r = dict(
                conn.execute(
                    "SELECT CASE WHEN ticket_type='ordinary' THEN 'ord' ELSE 'disc' END, SUM(head_count) "
                    'FROM attendance_count ac JOIN activity a USING(activity_id) JOIN event e USING(event_id) '
                    f"WHERE {where} AND ticket_type IN ('ordinary','member','concession','member_or_concession') "
                    'GROUP BY 1'
                ).fetchall()
            )
            n = r.get('disc', 0) + r.get('ord', 0)
            return r.get('disc', 0) / n, n

        f_l1, n_l1 = disc_named("a.difficulty='Level 1' AND e.event_type='course'")
        f_l2, n_l2 = disc_agg("a.difficulty='Level 2' AND e.event_type='course'")
        f_soc, n_soc = disc_named("e.event_type='social' AND e.name NOT LIKE '%30 Years%'")
        f_wk, n_wk = disc_named("e.event_type='weekender'")

        # ---- Recurring weekender audience: the biggest past weekender's retained crowd + its ticket mix ----
        wk_eid, wk_name, wk_last = conn.execute(
            'SELECT e.event_id, e.name, MAX(a.date) FROM event e JOIN activity a USING(event_id) '
            "JOIN attendance at ON at.activity_id = a.activity_id AND at.status IN ('attended','unknown') "
            "WHERE e.event_type='weekender' GROUP BY e.event_id ORDER BY COUNT(DISTINCT at.dancer_id) DESC LIMIT 1"
        ).fetchone()
        att_ref = {
            r[0]
            for r in conn.execute(
                'SELECT DISTINCT at.dancer_id FROM attendance at JOIN activity a USING(activity_id) '
                "WHERE a.event_id = ? AND at.status IN ('attended','unknown')",
                (wk_eid,),
            )
        }
        after = {
            r[0]
            for r in conn.execute(
                'SELECT DISTINCT at.dancer_id FROM attendance at JOIN activity a USING(activity_id) '
                "WHERE a.date > ? AND at.status='attended'",
                (wk_last,),
            )
        }
        ns = [
            n
            for (_, n) in conn.execute(
                'SELECT at.dancer_id, COUNT(DISTINCT a.activity_id) FROM attendance at '
                'JOIN activity a USING(activity_id) '
                "WHERE a.event_id = ? AND at.status IN ('attended','unknown') GROUP BY at.dancer_id",
                (wk_eid,),
            )
        ]
        mx, tot = max(ns), len(ns)
        rr = len(att_ref & after)
        wk_mix = {
            'reference': wk_name,
            'attendees_ref': tot,
            'retained': rr,
            'full': round(rr * sum(n >= mx - 1 for n in ns) / tot),
            'single': round(rr * sum(n == 1 for n in ns) / tot),
        }
        wk_mix['partial'] = rr - wk_mix['full'] - wk_mix['single']

        # ---- Level 2 loyalty survival: family chosen on the smooth all-activity curve, refit to L2 ----
        all_nights = [
            n
            for (n,) in conn.execute(
                'SELECT COUNT(DISTINCT a.date) FROM attendance at JOIN activity a USING(activity_id) '
                "WHERE at.status='attended' AND a.date >= '2026-01-01' GROUP BY at.dancer_id"
            )
        ]
        l2_nights = [
            n
            for (n,) in conn.execute(
                'SELECT COUNT(DISTINCT a.date) FROM attendance at JOIN activity a USING(activity_id) '
                "JOIN event e USING(event_id) WHERE a.difficulty='Level 2' AND e.event_type='course' "
                "AND at.status='attended' AND a.date >= '2026-01-01' GROUP BY at.dancer_id"
            )
        ]
        obs_thu = conn.execute(
            'SELECT COUNT(DISTINCT a.date) FROM activity a JOIN event e USING(event_id) '
            "WHERE a.difficulty='Level 2' AND e.event_type='course' AND a.date >= '2026-01-01'"
        ).fetchone()[0]

    ks_all, s_all = _survival(all_nights)
    best = max(_FAMILIES, key=lambda nm: _fit_family(nm, ks_all, s_all)[1])
    ks_l2, s_l2 = _survival(l2_nights)
    popt_l2, r2_l2 = _fit_family(best, ks_l2, s_l2)
    f_best = _FAMILIES[best][0]
    survival_l2 = {
        'k': ks_l2.tolist(),
        'empirical': s_l2.tolist(),
        'fit': [float(f_best(k, *popt_l2)) for k in ks_l2],
        'r2': r2_l2,
        'family': best,
    }

    l1_history = [
        {'ay': r['ay'], 'pos': r['pos'], 'interest': r['interest']} for r in l1_rows if r['ay'] >= _FIRST_FULL_YEAR
    ]

    return ForecastContext(
        beta=beta,
        s2=s2,
        xtxi=xtxi,
        dof=dof,
        l1_attend_curve=l1_attend_curve,
        l1_history=l1_history,
        l2_vals=l2_vals,
        soc_vals=soc_vals,
        xmas_vals=xmas_vals,
        social_only_vals=social_only_vals,
        wk_mix=wk_mix,
        fractions={'l1': f_l1, 'l2': f_l2, 'soc': f_soc, 'wk': f_wk},
        frac_n={'l1': n_l1, 'l2': n_l2, 'soc': n_soc, 'wk': n_wk},
        loyalty_family=best,
        loyalty_popt=[float(p) for p in popt_l2],
        loyalty_n_dancers=len(l2_nights),
        loyalty_obs_thu=obs_thu,
        survival_l2=survival_l2,
        defaults=_load_defaults(),
    )


def get_context(force_rebuild: bool = False) -> ForecastContext:
    """Return the cached forecast context, building it from the DB + defaults on first use."""
    global _CONTEXT
    with _LOCK:
        if _CONTEXT is None or force_rebuild:
            _CONTEXT = _build_context()
    return _CONTEXT


# --------------------------------------------------------------------------------------------------
# Parameters the committee can change (defaults come from the spreadsheet; provenance shown in the UI)
# --------------------------------------------------------------------------------------------------
def default_params(ctx: ForecastContext) -> dict:
    """The full editable parameter set at its forecast defaults (spreadsheet values)."""
    return dict(ctx.defaults)


def _pred_var(vals) -> float:
    v = np.asarray(vals, float)
    return float(v.var(ddof=1) * (1 + 1 / len(v)))


def _l1_pred(ctx: ForecastContext, ay: int) -> list[tuple[float, float]]:
    """Predicted Level 1 interest (mean, predictive-sd) for each of the six terms at forecast year ``ay``."""
    out = []
    for pos in range(1, 7):
        x0 = np.array([1.0, ay - 2024, *[1.0 if pos == p else 0.0 for p in range(2, 7)]])
        yh = float(x0 @ ctx.beta)
        var = ctx.s2 * (1 + x0 @ ctx.xtxi @ x0)
        out.append((max(yh, 0.0), float(np.sqrt(var))))
    return out


def _sigma_l1(ctx: ForecastContext, ay: int) -> np.ndarray:
    rows = [np.array([1.0, ay - 2024, *[1.0 if p == pp else 0.0 for pp in range(2, 7)]]) for p in range(1, 7)]
    return ctx.s2 * np.array([[xi @ ctx.xtxi @ xj for xj in rows] for xi in rows]) + np.eye(6) * ctx.s2


def _loyalty_refunds(ctx: ForecastContext, loyalty_every: int, fc_l2_thu: int) -> float:
    """Projected yearly Level 2 loyalty refunds = n_dancers * sum_m S(every * m), stretched to the year."""
    f = _FAMILIES[ctx.loyalty_family][0]
    thr_scale = ctx.loyalty_obs_thu / fc_l2_thu
    total, m = 0.0, 1
    while (s := f(loyalty_every * m * thr_scale, *ctx.loyalty_popt)) > _SURVIVAL_EPS and (
        loyalty_every * m * thr_scale <= _MAX_SURVIVAL_NIGHTS
    ):
        total += s
        m += 1
    return ctx.loyalty_n_dancers * total


# --------------------------------------------------------------------------------------------------
# The money ledger (pure Python so 2n+1 sigma-point evaluations stay fast)
# --------------------------------------------------------------------------------------------------
def _blended(disc, ordinary, f_disc):
    return f_disc * disc + (1 - f_disc) * ordinary


def run_scenario(ctx: ForecastContext, p: dict, cal: dict, socials: list, x: np.ndarray) -> dict:  # noqa: C901, PLR0912, PLR0915
    """Build the full-year ledger from parameters ``p`` and the uncertain input vector ``x``.

    ``x`` holds the 18 uncertain quantities in ``INPUT_NAMES`` order. Returns the year net, the
    per-category revenue/cost split, and the running bank balance (dated moves).
    """
    l1_signups = [max(0.0, v) for v in x[:6]]
    l2_att, soc_att, xmas_att, social_only, wk_ret, n_mem = (max(0.0, float(v)) for v in x[6:12])
    fl1, fl2, fsoc, fwk = (min(1.0, max(0.0, float(v))) for v in x[12:16])
    loyalty_refunds = max(0.0, float(x[16]))
    band_cost = max(0.0, float(x[17]))

    dc_rate, dc_fixed, dc_cap = p['dc_rate'], p['dc_fixed'], p['dc_cap']
    stripe_rate, stripe_fixed = p['stripe_rate'], p['stripe_fixed']

    def dc_fee(amount):
        return min(dc_rate * amount + dc_fixed, dc_cap)

    ledger = []  # (date, category, kind, gross, dcfee, cost, is_loyalty)

    def add(dt, cat, kind, gross=0.0, n_txn=0, ticket_amt=0.0, cost=0.0, is_loyalty=False):  # noqa: PLR0913
        ledger.append((dt, cat, kind, gross, n_txn * dc_fee(ticket_amt) if n_txn else 0.0, cost, is_loyalty))

    fc_l2_thu = sum(t['weeks'] for t in cal['terms'])
    class_venue = (p['class_room_hour_a'] + p['class_room_hour_b']) * p['room_per_hour']
    class_teachers = (p['teacher_hours_a'] + p['teacher_hours_b'] + p['teacher_hours_c'] + p['teacher_hours_d']) * p[
        'teacher_rate'
    ]
    class_price = _blended(p['price_class_disc'], p['price_class_ord'], fl1)
    l2_price = _blended(p['price_class_disc'], p['price_class_ord'], fl2)
    social_only_price = _blended(p['price_social_only_disc'], p['price_social_only_ord'], fsoc)
    loyalty_per_thu = loyalty_refunds * l2_price / fc_l2_thu
    cap = p.get('class_size_cap') or None

    add(
        cal['first_class'],
        'Memberships',
        'revenue',
        gross=n_mem * p['membership_fee'],
        n_txn=round(n_mem),
        ticket_amt=p['membership_fee'],
    )

    for t in cal['terms']:
        signups = l1_signups[t['term'] - 1]
        if cap is not None:
            signups = min(signups, cap)
        if not p['l1_per_night']:
            block = t['weeks'] * class_price
            add(t['start'], 'Level 1 classes', 'revenue', gross=signups * block, n_txn=round(signups), ticket_amt=block)
        for w, thu in enumerate(t['thursdays']):
            if p['l1_per_night']:
                la = signups * (ctx.l1_attend_curve[w] if w < len(ctx.l1_attend_curve) else ctx.l1_attend_curve[-1])
                add(thu, 'Level 1 classes', 'revenue', gross=la * class_price, n_txn=round(la), ticket_amt=class_price)
            add(thu, 'Level 2 classes', 'revenue', gross=l2_att * l2_price, n_txn=round(l2_att), ticket_amt=l2_price)
            add(
                thu,
                'Social-only tickets',
                'revenue',
                gross=social_only * social_only_price,
                n_txn=round(social_only),
                ticket_amt=social_only_price,
            )
            add(thu, 'Class venue', 'cost', cost=class_venue)
            add(thu, 'Class teachers', 'cost', cost=class_teachers)
            if p['loyalty_enabled']:
                add(thu, 'Loyalty refunds', 'cost', cost=loyalty_per_thu, is_loyalty=True)

    wk_full = wk_ret * ctx.wk_mix['full'] / ctx.wk_mix['retained']
    wk_partial = wk_ret * ctx.wk_mix['partial'] / ctx.wk_mix['retained']
    wk_single = wk_ret * ctx.wk_mix['single'] / ctx.wk_mix['retained']
    for label, dt in socials:
        if label == 'Weekender':
            for n, pd_, po in [
                (wk_full, p['price_wk_full_disc'], p['price_wk_full_ord']),
                (wk_partial, p['price_wk_day_disc'], p['price_wk_day_ord']),
                (wk_single, p['price_social_disc'], p['price_social_ord']),
            ]:
                price = _blended(pd_, po, fwk)
                add(dt, 'Weekender tickets', 'revenue', gross=n * price, n_txn=round(n), ticket_amt=price)
            add(dt, 'Weekender costs', 'cost', cost=p['weekender_bands'] * band_cost)
            add(dt, 'Weekender costs', 'cost', cost=p['weekender_bands'] * p['social_snacks'])
            add(dt, 'Weekender costs', 'cost', cost=p['weekender_room_hours'] * p['room_per_hour'])
            add(
                dt,
                'Weekender costs',
                'cost',
                cost=p['weekender_teachers'] * p['weekender_teacher_rate'] * p['weekender_teacher_hours'],
            )
            add(dt, 'Weekender costs', 'cost', cost=p['weekender_teachers'] * p['weekender_flight'])
            add(
                dt,
                'Weekender costs',
                'cost',
                cost=p['weekender_teachers'] * p['weekender_board_per_night'] * p['weekender_nights'],
            )
        else:
            att = xmas_att if label == 'Christmas party' else soc_att
            price = _blended(p['price_social_disc'], p['price_social_ord'], fsoc)
            add(dt, 'Social tickets', 'revenue', gross=att * price, n_txn=round(att), ticket_amt=price)
            add(dt, 'Social costs', 'cost', cost=band_cost)
            add(dt, 'Social costs', 'cost', cost=p['social_snacks'])
            add(dt, 'Social costs', 'cost', cost=p['social_room_hours'] * p['room_per_hour'])

    vol_heads = p['n_committee'] + p['n_safer_spaces'] + p['n_extra_volunteers']
    for party in (cal['xmas_party'], cal['eoy_party']):
        add(party - timedelta(days=7), 'Volunteer socials', 'cost', cost=vol_heads * p['volunteer_social_per_head'])

    n_seats = p['n_committee'] + p['n_safer_spaces'] + p['n_legacy_accounts'] + p['n_shared_accounts']
    overheads = {k: p['oh_' + k] for k in OVERHEAD_KEYS}
    overheads['google_workspace'] = n_seats * p['gsuite_seat_monthly'] * 12 + p['wix_reseller_annual']
    oh_months = [date(cal['ay'] if m >= _SEPTEMBER else cal['ay'] + 1, m, 1) for m in (9, 10, 11, 12, 1, 2, 3, 4, 5, 6)]
    for name, amt in overheads.items():
        for dt in oh_months:
            add(dt, 'Overheads', 'cost', cost=amt / len(oh_months))

    # ---- Fees and the daily bank balance ----
    total_gross = sum(r[3] for r in ledger)
    total_dc = sum(r[4] for r in ledger)
    total_cost = sum(r[5] for r in ledger)

    # Stripe: 1.5% + 20p on the cash transferred to us each day (income net of Dancecloud, less loyalty
    # refunds that never arrive); charged separately from Dancecloud and settling daily.
    daily_stripe_base: dict[date, float] = {}
    daily_delta: dict[date, float] = {}
    for dt, cat, kind, gross, dcfee, cost, is_loyalty in ledger:
        net_in = gross - dcfee
        base = -cost if is_loyalty else net_in
        daily_stripe_base[dt] = daily_stripe_base.get(dt, 0.0) + base
        daily_delta[dt] = daily_delta.get(dt, 0.0) + net_in - cost
    total_stripe = 0.0
    for dt, base in daily_stripe_base.items():
        if base > 0:
            fee = stripe_rate * base + stripe_fixed
            total_stripe += fee
            daily_delta[dt] = daily_delta.get(dt, 0.0) - fee

    net = total_gross - total_dc - total_stripe - total_cost
    balance, running = [], float(p['current_balance'])
    for dt in sorted(daily_delta):
        running += daily_delta[dt]
        balance.append((dt, running))

    return {'net': net, 'ledger': ledger, 'balance': balance, 'total_dc': total_dc, 'total_stripe': total_stripe}


def _budget(scenario: dict) -> list[dict]:
    """Aggregate the point-estimate ledger into revenue and cost lines, largest first."""
    rev: dict[str, float] = {}
    cost: dict[str, float] = {}
    for _dt, cat, kind, gross, _dcfee, c, _loy in scenario['ledger']:
        if gross:
            rev[cat] = rev.get(cat, 0.0) + gross
        if c:
            cost[cat] = cost.get(cat, 0.0) + c
    cost['Dancecloud fees'] = scenario['total_dc']
    cost['Stripe fees'] = scenario['total_stripe']
    lines = [
        {'category': k, 'amount': round(v), 'kind': 'revenue'} for k, v in sorted(rev.items(), key=lambda i: -i[1])
    ]
    lines += [{'category': k, 'amount': round(v), 'kind': 'cost'} for k, v in sorted(cost.items(), key=lambda i: -i[1])]
    return lines


# --------------------------------------------------------------------------------------------------
# Uncertainty: assemble the input distribution and push it through with the unscented transform
# --------------------------------------------------------------------------------------------------
def _mu_sigma(ctx: ForecastContext, p: dict, cal: dict) -> tuple[np.ndarray, np.ndarray]:
    l1 = _l1_pred(ctx, cal['ay'])
    fc_l2_thu = sum(t['weeks'] for t in cal['terms'])
    loyalty = _loyalty_refunds(ctx, p['loyalty_every'], fc_l2_thu) if p['loyalty_enabled'] else 0.0
    mu = np.array(
        [m for m, _ in l1]
        + [
            float(np.mean(ctx.l2_vals)),
            float(np.mean(ctx.soc_vals)),
            float(np.mean(ctx.xmas_vals)),
            float(np.mean(ctx.social_only_vals)),
            ctx.wk_mix['retained'],
            p['n_members'],
            ctx.fractions['l1'],
            ctx.fractions['l2'],
            ctx.fractions['soc'],
            ctx.fractions['wk'],
            loyalty,
            p['band_cost_mean'],
        ]
    )
    wk_n, wk_p = ctx.wk_mix['attendees_ref'], ctx.wk_mix['retained'] / ctx.wk_mix['attendees_ref']
    f, fn = ctx.fractions, ctx.frac_n
    diag = [
        _pred_var(ctx.l2_vals),
        _pred_var(ctx.soc_vals),
        _pred_var(ctx.xmas_vals),
        _pred_var(ctx.social_only_vals),
        wk_n * wk_p * (1 - wk_p),
        p['membership_std'] ** 2,
        f['l1'] * (1 - f['l1']) / fn['l1'],
        f['l2'] * (1 - f['l2']) / fn['l2'],
        f['soc'] * (1 - f['soc']) / fn['soc'],
        f['wk'] * (1 - f['wk']) / fn['wk'],
        loyalty,
        p['band_cost_std'] ** 2,
    ]
    sigma = np.zeros((len(mu), len(mu)))
    sigma[:6, :6] = _sigma_l1(ctx, cal['ay'])
    for i, v in enumerate(diag):
        sigma[6 + i, 6 + i] = v
    return mu, sigma


def _unscented(ctx, p, cal, socials, mu, sigma):
    """Propagate (mu, sigma) through run_scenario with 2n+1 sigma points.

    The sigma point at ``mu`` is the deterministic point estimate; we report standard deviations from
    the unscented weights but keep the *centre* on that point estimate, so the headline and the balance
    curve reconcile with the itemised budget (which is the point estimate) rather than drifting a few
    pounds away through the transform's nonlinearity.
    """
    n = len(mu)
    alpha, beta_, kappa = 0.5, 2.0, 0.0
    lam = alpha**2 * (n + kappa) - n
    # A toggle can zero an input's variance (e.g. disabling the loyalty scheme), leaving the covariance
    # only positive-semidefinite; a tiny jitter keeps the Cholesky well-defined. Such inputs don't move
    # the output, so the jitter is numerically negligible.
    chol = np.linalg.cholesky((n + lam) * (sigma + np.eye(n) * 1e-6))
    pts = np.vstack([mu, mu + chol.T, mu - chol.T])
    wm = np.full(2 * n + 1, 1 / (2 * (n + lam)))
    wc = wm.copy()
    wm[0] = lam / (n + lam)
    wc[0] = wm[0] + (1 - alpha**2 + beta_)

    scenarios = [run_scenario(ctx, p, cal, socials, x) for x in pts]
    nets = np.array([s['net'] for s in scenarios])
    net_mean = float(wm @ nets)
    net_std = float(np.sqrt(max(wc @ (nets - net_mean) ** 2, 0.0)))

    grid = [dt for dt, _ in scenarios[0]['balance']]  # point-estimate date grid
    mat = np.array([_balance_on_grid(s['balance'], grid, float(p['current_balance'])) for s in scenarios])
    bal_mean = wm @ mat
    bal_std = np.sqrt(np.clip(wc @ (mat - bal_mean) ** 2, 0, None))
    return {'net_std': net_std, 'grid': grid, 'bal_std': bal_std}


def _balance_on_grid(balance, grid, opening):
    d = [dt for dt, _ in balance]
    b = [v for _, v in balance]
    out = []
    for g in grid:
        idx = -1
        for i, dt in enumerate(d):
            if dt <= g:
                idx = i
            else:
                break
        out.append(b[idx] if idx >= 0 else opening)
    return out


def _contributors(ctx, p, cal, socials, mu, sigma):
    """Variance decomposition: share of year-net variance from each input (grouping the L1 block)."""
    n = len(mu)
    sd = np.sqrt(np.diag(sigma))
    j = np.zeros(n)
    for i in range(n):
        step = sd[i] if sd[i] > 0 else 1.0
        e = np.zeros(n)
        e[i] = step
        hi = run_scenario(ctx, p, cal, socials, mu + e)['net']
        lo = run_scenario(ctx, p, cal, socials, mu - e)['net']
        j[i] = (hi - lo) / (2 * step)
    var_total = float(j @ sigma @ j) or 1.0
    contrib = {'Level 1 sign-ups': float(j[:6] @ sigma[:6, :6] @ j[:6])}
    for i in range(6, n):
        contrib[INPUT_NAMES[i]] = float(j[i] ** 2 * sigma[i, i])
    ranked = sorted(contrib.items(), key=lambda kv: -kv[1])
    return [{'name': k, 'pct': round(100 * v / var_total, 1)} for k, v in ranked if v > 0]


# --------------------------------------------------------------------------------------------------
# The public entry point
# --------------------------------------------------------------------------------------------------
def _merge_params(ctx: ForecastContext, overrides: dict) -> dict:
    """Start from the spreadsheet defaults and apply the caller's overrides, coercing types."""
    p = dict(ctx.defaults)
    bool_keys = {'have_weekender', 'loyalty_enabled', 'l1_per_night'}
    int_keys = {
        'forecast_ay',
        'n_tea_dances',
        'loyalty_every',
        'n_committee',
        'n_safer_spaces',
        'n_extra_volunteers',
        'n_legacy_accounts',
        'n_shared_accounts',
    }
    for k, v in (overrides or {}).items():
        if k not in p or v is None:
            continue
        if k in bool_keys:
            p[k] = bool(v) if not isinstance(v, str) else v.lower() in ('true', '1', 'yes', 'on')
        elif k in int_keys:
            p[k] = int(round(float(v)))
        elif k == 'class_size_cap':
            p[k] = None if v in ('', None) else int(round(float(v)))
        else:
            p[k] = float(v)
    return p


def predict(overrides: dict | None = None, confidence: float | None = None) -> dict:
    """Run the forecast for the given parameter overrides and confidence level.

    Returns the budget breakdown, the net and year-end balance with a confidence interval, the balance
    curve with an uncertainty band, the variance decomposition, and the detailed attendance models.
    """
    ctx = get_context()
    p = _merge_params(ctx, overrides)
    conf = float(confidence if confidence is not None else p.get('confidence', 0.95))
    conf = min(0.999, max(0.5, conf))
    z = _z(conf)

    cal = build_calendar(int(p['forecast_ay']))
    socials = place_socials(cal, int(p['n_tea_dances']), bool(p['have_weekender']))
    mu, sigma = _mu_sigma(ctx, p, cal)

    point = run_scenario(ctx, p, cal, socials, mu)
    ut = _unscented(ctx, p, cal, socials, mu, sigma)

    # Centre on the deterministic point estimate (which the itemised budget reconciles with); the
    # unscented transform supplies the standard deviations for the confidence band.
    net_mean, net_std = float(point['net']), ut['net_std']
    p_green = float(stats.norm.cdf(net_mean / net_std)) if net_std > 0 else (1.0 if net_mean > 0 else 0.0)
    point_bal = _balance_on_grid(point['balance'], ut['grid'], float(p['current_balance']))
    ye_mean, ye_std = point_bal[-1], net_std

    balance = {
        'dates': [dt.isoformat() for dt in ut['grid']],
        'mean': [round(v) for v in point_bal],
        'lo': [round(v - z * s) for v, s in zip(point_bal, ut['bal_std'])],
        'hi': [round(v + z * s) for v, s in zip(point_bal, ut['bal_std'])],
        'opening': round(float(p['current_balance'])),
    }
    l1 = _l1_pred(ctx, cal['ay'])
    return {
        'confidence': conf,
        'net': {
            'mean': round(net_mean),
            'lo': round(net_mean - z * net_std),
            'hi': round(net_mean + z * net_std),
            'std': round(net_std),
        },
        'year_end_balance': {
            'mean': round(ye_mean),
            'lo': round(ye_mean - z * ye_std),
            'hi': round(ye_mean + z * ye_std),
        },
        'p_green': round(p_green, 3),
        'budget': _budget(point),
        'balance': balance,
        'contributors': _contributors(ctx, p, cal, socials, mu, sigma),
        'calendar': {
            'ay': cal['ay'],
            'n_class_nights': sum(t['weeks'] for t in cal['terms']),
            'socials': [{'label': lbl, 'date': dt.isoformat()} for lbl, dt in socials],
            'terms': [
                {'term': t['term'], 'start': t['start'].isoformat(), 'end': t['end'].isoformat(), 'weeks': t['weeks']}
                for t in cal['terms']
            ],
        },
        'detail': {
            'l1_signups': [
                {'term': i + 1, 'mean': round(m, 1), 'lo': round(max(m - z * s, 0), 1), 'hi': round(m + z * s, 1)}
                for i, (m, s) in enumerate(l1)
            ],
            'l1_history': ctx.l1_history,
            'l2_survival': ctx.survival_l2,
            'loyalty_every': int(p['loyalty_every']),
            'inputs': [
                {'name': INPUT_NAMES[i], 'mean': round(float(mu[i]), 3), 'sd': round(float(np.sqrt(sigma[i, i])), 3)}
                for i in range(len(mu))
            ],
        },
    }


# --------------------------------------------------------------------------------------------------
# Download the whole scenario as a timestamped workbook
# --------------------------------------------------------------------------------------------------
def to_workbook(overrides: dict | None, confidence: float | None) -> bytes:
    """Serialise the current scenario (inputs + results) to an .xlsx for saving a what-if variant."""
    ctx = get_context()
    p = _merge_params(ctx, overrides)
    result = predict(overrides, confidence)

    wb = openpyxl.Workbook()
    meta = wb.active
    meta.title = 'summary'
    meta.append(['ESDS forecast scenario'])
    meta.append(['generated', datetime.datetime.now().isoformat(timespec='seconds')])
    meta.append(['confidence', result['confidence']])
    meta.append([])
    meta.append(['metric', 'mean', 'low', 'high'])
    meta.append(['year net', result['net']['mean'], result['net']['lo'], result['net']['hi']])
    meta.append(
        [
            'year-end balance',
            result['year_end_balance']['mean'],
            result['year_end_balance']['lo'],
            result['year_end_balance']['hi'],
        ]
    )
    meta.append(['probability of surplus', result['p_green']])

    budget = wb.create_sheet('budget')
    budget.append(['category', 'kind', 'amount'])
    for line in result['budget']:
        budget.append([line['category'], line['kind'], line['amount']])

    params = wb.create_sheet('parameters')
    params.append(['parameter', 'value'])
    for k in sorted(p):
        params.append([k, p[k]])

    bal = wb.create_sheet('balance')
    bal.append(['date', 'mean', 'low', 'high'])
    b = result['balance']
    for dt, m, lo, hi in zip(b['dates'], b['mean'], b['lo'], b['hi']):
        bal.append([dt, m, lo, hi])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
